emacs \
screen/Screen.h.orig \
io/Motor.h \
io/Motor.c \
test/PortMonitor.c \
test/MotorPWMCmd.c \
test/AD9834Test.c \
test/StepperPulse.c \
test/PulseGenerator.c \
test/MotorCmd.c \
test/SetOutput.c \
test/EncoderTest.c \
